ports:
  - port: 8000
    onOpen: open-preview

tasks:
  - name: Install Symfony cli
    command: wget https://get.symfony.com/cli/installer -O - | bash
  - name: Set Path for Symfony cli
    command: export PATH="$HOME/.symfony/bin:$PATH"
  - name: Install dependencies and start dev server
    init: |
      composer update
      yarn install --ignore-engines
      npm run watch
    command: symfony server:start
